version: '3'

tasks:
  collect-and-run-tests:
    desc: "Collect and run tests workflows"
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        echo "Collecting test workflows"
        TEST_FLOWS=$(find ./resources -name "*_test.job.yml" -exec basename {} .job.yml \; | tr '\n' ',' | sed 's/,$//')
        if [ -z "$TEST_FLOWS" ]; then
          echo "No test workflows found."
          exit 0
        fi
        echo "Test flows found: $TEST_FLOWS"
        export TEST_FLOWS
      - |
        echo "Running test workflows"
        IFS=',' read -r -a FLOWS <<< "$TEST_FLOWS"
        for flow in "${FLOWS[@]}"; do
          if [ -n "$flow" ]; then
            echo "Running test flow: $flow"
            databricks bundle run -t {{.ENV}} "$flow"
            if [ $? -ne 0 ]; then
              echo "Test flow $flow failed. Stopping further execution."
              exit 1
            fi
          fi
        done
