version: '3'

tasks:
  collect-tests:
    desc: "Collect test workflows"
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        echo "Collecting test workflows"
        TEST_FLOWS=$(find ./resources -name "*_test.job.yml" -exec basename {} .job.yml \; | tr '\n' ',' | sed 's/,$//')
        if [ -z "$TEST_FLOWS" ]; then
          echo "No test workflows found."
          exit 0
        fi
        echo "Test flows found: $TEST_FLOWS"
        echo "test_flows=$TEST_FLOWS" >> $GITHUB_ENV
  
  run-tests:
    desc: "Run Databricks test workflows"
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
       - |
        # Ensure the test_flows environment variable is set
        if [ -z "{{.test_flows}}" ]; then
          echo "No test flows provided."
          exit 0
        fi
        
        echo "Test flows to run: {{.test_flows}}"
        
        #Read test flows into an array
        IFS=',' read -ra FLOWS <<< "{{.test_flows}}"
        
        # Loop through each test flow and run it
        for flow in "${FLOWS[@]}"; do
          if [ -n "$flow" ]; then
            echo "Running test flow: $flow"
            databricks bundle run -t {{.ENV}} "$flow"
          fi
        done