version: '3'

tasks:
  collect-tests:
    desc: "Collect test workflows"
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        echo "Collecting test workflows"
        TEST_FLOWS=$(find ./resources -name "*_test.job.yml" -exec basename {} .job.yml \; | tr '\n' ',' | sed 's/,$//')
        if [ -z "$TEST_FLOWS" ]; then
          echo "No test workflows found."
          exit 0
        fi
        echo "Test flows found: $TEST_FLOWS"
        echo "test_flows=$TEST_FLOWS" >> $GITHUB_ENV