name: "Int Deployment"

concurrency: 1

on:
  workflow_run:
    workflows: ["Dev Deployment"]
    types:
      - completed
      
env:
  ENV: int

jobs:
  deploy:
    name: "Deploy to Staging"
    runs-on: ubuntu-latest
    environment: int
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Check out this repo
      - uses: actions/checkout@v4

      # Login to Azure Portal Using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_INT_CREDENTIALS }}

      # Download the Databricks CLI
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "stg" target
      - name: Deploy Databricks Bundle
        run: |
          databricks bundle validate -t ${{ env.ENV }}
          databricks bundle deploy -t ${{ env.ENV }}
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}

      - name: run databricks test workflow
        run: |
          databricks bundle run -t ${{ env.ENV }} Test_Flow
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV}}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}