name: "Dev Deployment"

concurrency: 1

on:
  workflow_run:
    workflows: ["CI Linting"]
    types:
      - completed
env:
  ENV: dev

jobs:
  # Used by the "pipeline_update" job to deploy the bundle.
  # Bundle validation is automatically performed as part of this deployment.
  # If validation fails, this workflow fails.
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: development
    if: |
      github.event.workflow_run.conclusion == 'success'

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v4

      # Login to Azure Portal Using Service Principal
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}

      # Download the Databricks CLI.
      - uses: databricks/setup-cli@main


      # Deploy the bundle to the "dev" target as defined
      # in the bundle's settings file.
      - run: |
            databricks bundle validate
            databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV}}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}

      # Find all test workflows starting with "Test_", remove .yml extension, and save them as a comma-separated list
      - name: Set Test Flows
        id: set_test_flows
        run: |
          TEST_FLOWS=$(find . -name "*_test.yml" -exec basename {} .yml \; | tr '\n' ',' | sed 's/,$//')
          echo "test_flows=$TEST_FLOWS" >> $GITHUB_ENV

      - name: Run databricks test workflows
        run: |
          IFS=',' read -ra FLOWS <<< "${{ env.test_flows }}"
          for flow in "${FLOWS[@]}"; do
            echo "Running test flow: $flow"
            databricks bundle run -t ${{ env.ENV }} "$flow"
          done
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}