name: Staging Workflow

on:
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/templates/databricks-validate.yml
    with:
      env: staging

  deploy:
    uses: ./.github/workflows/templates/databricks-deploy.yml
    with:
      env: staging
    secrets:
      azure_credentials: ${{ secrets.AZURE_STG_CREDENTIALS }}
