name: Staging Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/databricks-deploy.yml
    with:
      env: staging
    secrets:
      azure_credentials: ${{ secrets.AZURE_STG_CREDENTIALS }}
