name: CI Workflow with uv, Python 3.11, and Ruff Linting
run-name: Linting and Testing Datarbicks Source Code by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
    paths:  
      - 'src/**'
      - 'tests/**'

env:
  UV_VERSION: ">=0.4.26"

jobs:
  uv-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
          cache-dependency-glob: "**/requirements**.txt"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.0.259
          args: check
          src: "./src"
        
      - name: Run tests
        run: uv run pytest
      
