name: "Sandbox Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ENV: int

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: int

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Azure Login Using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_INT_CREDENTIALS }}

      - name: Deploy Databricks Bundle
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            databricks bundle validate -t ${{ env.ENV }}
          elif [ "${{ github.event_name }}" == "push" ]; then
            databricks bundle deploy -t ${{ env.ENV }}
          fi
        working-directory: .
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}

      - name: Set Test Flows
        run: |
          TEST_FLOWS=$(find . -name "*_test.job.yml" -exec basename {} .job.yml \; | tr '\n' ',' | sed 's/,$//')
          echo "Test flows found: $TEST_FLOWS"
          echo "test_flows=$TEST_FLOWS" >> $GITHUB_ENV
  
      - name: Run databricks test workflows
        run: |
          echo "Test flows to run: ${{ env.test_flows }}"

          # Iterate over each test flow and run with `databricks bundle run`
          IFS=',' read -ra FLOWS <<< "${{ env.test_flows }}"
          for flow in "${FLOWS[@]}"; do
            if [ -n "$flow" ]; then  # Ensure flow is not empty
              echo "Running test flow: $flow"
              databricks bundle run -t ${{ env.ENV }} "$flow"
            fi
          done
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}
