name: CI Workflow with uv, Python 3.11, and Ruff Linting
run-name: Linting and Testing Datarbicks Source Code by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
    paths:  
      - 'src/**'
      - 'tests/**'

env:
  UV_VERSION: ">=0.4.26"
  PYTHON_VERSION: "3.11"



jobs:
  linting-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}
          cache-dependency-glob: "**/requirements**.txt"

      - name: Install Python and Dependencies
        run: | 
          uv python install ${{ env.PYTHON_VERSION }}
          uv tool install ruff
          uv tool install pytest
      
      - name: Run Ruff Lint
        run: |
          uv run ruff check
        
      - name: Run tests
        run: |
          uv run pytest
      
