name: "Dev Deployment"

on:
  workflow_run:
    workflows: ["Sandbox Deployment"]
    types:
      - completed

jobs:
  validate:
    if: |
      github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/databricks-validate.yml
    with:
      env: development

  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/databricks-deploy.yml
    with:
      env: development
    secrets:
      azure_credentials: ${{ secrets.AZURE_DEV_CREDENTIALS }}