name: Databricks Validation Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  validate:
    name: Validate Databricks Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks Bundle
        run: |
          echo "Validating Databricks bundle for ${{ inputs.env }} environment..."
          databricks bundle validate -t ${{ inputs.env }} -o json
