name: "Dev Deployment"

on:
  workflow_run:
    workflows: ["Sandbox Deployment"]
    types:
      - completed

jobs:
  deploy:
    uses: ./.github/workflows/databricks-deploy.yml
    with:
      env: dev
    secrets:
      azure_credentials: ${{ secrets.AZURE_DEV_CREDENTIALS }}