name: "Stg Deployment"

on:
  workflow_dispatch:

env:
  ENV: stg

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Azure Login Using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_DEV_CREDENTIALS }}

      - name: Validate Databricks Bundle
        id: validate_bundle
        run: |
          OUTPUT=$(databricks bundle validate -t ${{ env.ENV }} -o json)
          echo "$OUTPUT" > validation_output.json
          echo "Validation Output: $OUTPUT"
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}

      - name: Upload Validation Output
        uses: actions/upload-artifact@v3
        with:
          name: validation-output
          path: validation_output.json

      - name: Manual Approval
        if: always()
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Databricks Bundle
        if: success() && github.event.inputs.approved == 'true'
        run: |
          databricks bundle deploy -t ${{ env.ENV }}
        env:
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Test Flows
        run: task collect-tests

      - name: Run test workflows
        run: task run-tests
        env:
          # task file required variables
          test_flows: ${{ env.test_flows }}
          # bundle file required variables
          DATABRICKS_BUNDLE_ENV: ${{ env.ENV }}
          BUNDLE_VAR_ADB_HOST_URL: ${{ vars.ADB_HOST_URL }}
          BUNDLE_VAR_FILE_LANDING_URL: ${{ vars.FILE_LANDING_URL }}
