name: "Sandbox Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  UV_VERSION: ">=0.4.26"
  PYTHON_VERSION: "3.11"


jobs:
  lint:
    uses: ./.github/workflows/databricks-lint.yml
    with:
      uv_version: ${{ env.UV_VERSION }}
      python_version: ${{ env.PYTHON_VERSION }}

  deploy:
      if: github.event_name == 'push'
      uses: ./.github/workflows/reusable-deploy.yml
      with:
        env: dev
      secrets:
        azure_credentials: ${{ secrets.AZURE_INT_CREDENTIALS }}