name: "Sandbox Deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/templates/databricks-lint.yml
    with:
      uv_version: ">=0.4.26"
      python_version: "3.11"
  
  validate:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/templates/databricks-validate.yml
    with:
      env: int

  deploy:
      if: github.event_name == 'push'
      uses: ./.github/workflows/templates/databricks-deploy.yml
      with:
        env: int
      secrets:
        azure_credentials: ${{ secrets.AZURE_INT_CREDENTIALS }}